// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ectninllmvrndwymikky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjdG5pbmxsbXZybmR3eW1pa2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTcwNjksImV4cCI6MjA3MjkzMzA2OX0.RfY1TjgPKuewUCiq6ebeh24z2TcKBwmxelV08VksT4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});